sudo: false
language: python
python:
- '2.7'
env:
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=py27
- TOX_ENV=py26
install:
- pip install tox
script:
- tox -e $TOX_ENV
deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  on:
    branch: pypi-release
    condition: $TOX_ENV = py27
  user:
    secure: PYsz1O1/1pDK5VTebKA+O1Nw4uNlpitKs+id2NH526Dp5H96qfasD+eNi9QBkg9llnYO2xxV4qIfG9sHCGC5To7nUAH8lLmVdq6UPvXiCr9iAcMVmXqVL//CKOkjvsJqhFCQlCBcEDmz/nFshtE04ni6f5j3vbFIcYLPFgYUt9Q=
  password:
    secure: KXeI8u5g+zYXoz6KTm4yDYE1WyzqpEc5k13XPgT07VRzXutpEFHRKl/pdIpTuAxmJ/ok/92XFhRHzSpW3WFC+rd7P1H4GkCmOfU73oF3nO0ogI9LLsznuuPCNhc+ZoeEO8njW4FTr9UfJilcXZaJ4X1oGcoCx2NHOPztJLJsaZs=
after_deploy:
- git clone https://github.com/cloudify-cosmo/travis-utils.git
- python travis-utils/validate_pypi.py -v || exit 1
notifications:
  flowdock: 1f4ec6febcf1ac9b35ae6c1f0049471f
