language: python
python:
- '2.7'
env:
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=py27
- TOX_ENV=py26
install:
- pip install tox
script:
- tox -e $TOX_ENV
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  on:
    branch: pypi-release
    condition: $TOX_ENV = py27
  user:
    secure: BxsPT0rVV7D/rSnmZCVSYOhvE/AJFsBzTS2lzLLvjpZ3I19Ygv32/9p4QafAjtjst+3hUkR6R8EgXpK+Ws9RkSagAgIKj1qO0hamLZeaY5YC5J9blhd0as7tIX4LaYbVjaUyoflKyWWjHv0sq9NFbPWax4Xy8HNqvHlaYscmeaI=
  password:
    secure: aDkj0IebkMju394isJjEgjOS1lzu2CuDRGxPAvBR/kxK3+SkQ/8pIeshrzA5DDalkRmX3qzBlQXLSviBcEzSsHsu6c/JOcDmxS+16KfZJu5lfWw0pm6vODf8wmYEIPZGqo+QpSrDsvisQiCSZrdewZefQc5jExBltwgA/THhJJQ=
after_deploy:
- git clone https://github.com/cloudify-cosmo/travis-utils.git
- python travis-utils/validate_pypi.py -v || exit 1
notifications:
  flowdock: 1f4ec6febcf1ac9b35ae6c1f0049471f
